name: Dominic Meiser
markdown: kramdown
repository: d-meiser/d-meiser.github.io
gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css: syntax.css


port: 4000
safe: true
encoding: UTF-8

